FROM --platform=linux/arm/v7 node:14-alpine
LABEL org.opencontainers.image.description "First version of ebay-tracker-image for ARMv7!"

WORKDIR /app

COPY package*.json .
RUN npm install

COPY . .
CMD ["npm", "start"]